# Generated by Django 6.0.7 on 2026-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationsubmission",
            name="gender_estimate",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
